version: '3.7'
services:
  pydm:
    #image: lnlscon/pydm:1.6.5
    image: pydm:latest
    volumes:
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
    networks:
      hostnet: {}
    dns:
      - 10.0.0.71
      - 10.0.0.72
    environment:
      - DISPLAY
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

networks:
  hostnet:
    external: true
    name: host
